AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
  Exclude:
    - "bin/*"
    - Capfile
    - config/boot.rb
    - config/environment.rb
    - config/initializers/version.rb
    - config/environments/development.rb
    - db/schema.rb
    - "tmp/**/*"
    - Gemfile
    - Guardfile
    - Rakefile
    - node_modules/**/*
    - db/migrate/*

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Enabled: false
  Exclude:
    - "test/**/*"

Style/UnneededInterpolation:
  Enabled: false

Rails/Output:
  Enabled: false

Style/OptionalArguments:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/AndOr:
  Enabled: false

Rails/FilePath:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - "config/**/*"
    - "test/**/*"

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false
  Exclude:
    - "config/**/*"
    - "db/**/*"

Metrics/MethodLength:
  Enabled: false
  Max: 12
  Exclude:
    - "db/migrate/*"
    - "test/**/*"

Naming/VariableNumber:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Rails:
  Enabled: true

Rails/Validation:
  Enabled: false

Rails/ApplicationRecord:
  Exclude:
    - "db/migrate/**"

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
  Exclude:
    - "app/controllers/application_controller.rb"
    - "app/helpers/**/*_helper.rb"
    - "app/mailers/**/*_mailer.rb"
    - "app/models/application_record.rb"
    - "config/**/*"
    - "db/**/*"
    - "test/**/*"

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  AllowPredicates: true
